version: '3.1'

services: 
  app-server:
    env_file:
      - .env
    image: tandavala/challenge-encurtador-backend
    build: 
      context: .
      dockerfile: Dockerfile-dev
    container_name: app-server
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    command: ["npm", "run", "start:dev"]
    networks: 
      - challenge-encurtador_network
    depends_on: 
      - redis
      - postgres
  postgres:
    container_name: challenge-encurtador_postgres
    image: postgres
    restart: always
    networks: 
      - challenge-encurtador_network
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${RDS_USERNAME}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
      POSTGRES_DB: ${RDS_DB_NAME}
    ports: 
      - ${RDS_PORT}:${RDS_PORT}
  
  redis:
    container_name: challenge-encurtador_redis
    image: redis
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    networks: 
      - challenge-encurtador_network
    volumes: 
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  adminer:
    container_name: challenge-encurtador_adminer
    image: adminer
    restart: always
    networks: 
      - challenge-encurtador_network
    ports: 
      - ${ADMINER_PORT}:${ADMINER_PORT}

networks: 
  challenge-encurtador_network:
    driver: bridge

volumes: 
  redis-data:
    driver: local
  postgres-data:
    driver: local