version: '3.9'

services:
  app-server:
    env_file:
      - .env
    image: tandavala/challange-encurtador-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: app-server
    networks:
      - app-network
      
    ports:
      - ${SERVER_PORT}:${SERVER_PORT} 
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    container_name: challenge-encurtador_postgres
    image: postgres
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
  
  adminer:
    container_name: challenge-encurtador_adminer
    image: adminer
    networks:
      - app-network
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

networks:
  app-network:
    driver: bridge
volumes:
  postgres-data:
    driver: local