version: '3.9'

services: 
  test-server:
    env_file:
      - .env
    image: tandavala/challenge-encurtador-test
    build: 
      context: .
      dockerfile: Dockerfile-test
    container_name: test-server
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}

    networks: 
      - challenge-encurtador_network
 
networks: 
  challenge-encurtador_network:
    driver: bridge

