version: '3.1'

services: 
  test-server:
    env_file:
      - .env
    image: tandavala/challenge-encurtador-test
    build: 
      context: .
      dockerfile: Dockerfile-test
    container_name: app-server
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    command: ["npm", "test"]
    networks: 
      - challenge-encurtador_network
 

networks: 
  challenge-encurtador_network:
    driver: bridge

volumes: 
  redis-data:
    driver: local
  postgres-data:
    driver: local